// Code generated by protoc-gen-go. DO NOT EDIT.
// source: edge.proto

/*
Package edge is a generated protocol buffer package.

It is generated from these files:
	edge.proto

It has these top-level messages:
	GetNodesRequest
	GetNodesReply
	GetIngressesRequest
	GetIngressesReply
	MakeTransformerRequest
	MakeTransformerReply
	ReadRowsRequest
	ReadRowsReply
*/
package edge

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetNodesRequest struct {
}

func (m *GetNodesRequest) Reset()                    { *m = GetNodesRequest{} }
func (m *GetNodesRequest) String() string            { return proto.CompactTextString(m) }
func (*GetNodesRequest) ProtoMessage()               {}
func (*GetNodesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetNodesReply struct {
	Nodes []string `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *GetNodesReply) Reset()                    { *m = GetNodesReply{} }
func (m *GetNodesReply) String() string            { return proto.CompactTextString(m) }
func (*GetNodesReply) ProtoMessage()               {}
func (*GetNodesReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetNodesReply) GetNodes() []string {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type GetIngressesRequest struct {
	Node string `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
}

func (m *GetIngressesRequest) Reset()                    { *m = GetIngressesRequest{} }
func (m *GetIngressesRequest) String() string            { return proto.CompactTextString(m) }
func (*GetIngressesRequest) ProtoMessage()               {}
func (*GetIngressesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetIngressesRequest) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

type GetIngressesReply struct {
	Ingresses []string `protobuf:"bytes,1,rep,name=ingresses" json:"ingresses,omitempty"`
}

func (m *GetIngressesReply) Reset()                    { *m = GetIngressesReply{} }
func (m *GetIngressesReply) String() string            { return proto.CompactTextString(m) }
func (*GetIngressesReply) ProtoMessage()               {}
func (*GetIngressesReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetIngressesReply) GetIngresses() []string {
	if m != nil {
		return m.Ingresses
	}
	return nil
}

type MakeTransformerRequest struct {
	Node string `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
	// if set, then javascript transformer is created
	Javascript []byte `protobuf:"bytes,2,opt,name=javascript,proto3" json:"javascript,omitempty"`
}

func (m *MakeTransformerRequest) Reset()                    { *m = MakeTransformerRequest{} }
func (m *MakeTransformerRequest) String() string            { return proto.CompactTextString(m) }
func (*MakeTransformerRequest) ProtoMessage()               {}
func (*MakeTransformerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MakeTransformerRequest) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *MakeTransformerRequest) GetJavascript() []byte {
	if m != nil {
		return m.Javascript
	}
	return nil
}

type MakeTransformerReply struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *MakeTransformerReply) Reset()                    { *m = MakeTransformerReply{} }
func (m *MakeTransformerReply) String() string            { return proto.CompactTextString(m) }
func (*MakeTransformerReply) ProtoMessage()               {}
func (*MakeTransformerReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MakeTransformerReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadRowsRequest struct {
	Node          string `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
	Start         []byte `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End           []byte `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	TransformerId string `protobuf:"bytes,4,opt,name=transformer_id,json=transformerId" json:"transformer_id,omitempty"`
	Accumulator   string `protobuf:"bytes,5,opt,name=accumulator" json:"accumulator,omitempty"`
	// ReadRows will terminate after reading N rows worth of input. Note: transforms are not
	// 1:1 for input to output rows, so N rows of input may result in M rows of output.
	Limit int64 `protobuf:"varint,6,opt,name=limit" json:"limit,omitempty"`
}

func (m *ReadRowsRequest) Reset()                    { *m = ReadRowsRequest{} }
func (m *ReadRowsRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRowsRequest) ProtoMessage()               {}
func (*ReadRowsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ReadRowsRequest) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *ReadRowsRequest) GetStart() []byte {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *ReadRowsRequest) GetEnd() []byte {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *ReadRowsRequest) GetTransformerId() string {
	if m != nil {
		return m.TransformerId
	}
	return ""
}

func (m *ReadRowsRequest) GetAccumulator() string {
	if m != nil {
		return m.Accumulator
	}
	return ""
}

func (m *ReadRowsRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type ReadRowsReply struct {
	Rows []string `protobuf:"bytes,1,rep,name=rows" json:"rows,omitempty"`
	// optionally, the server might return the row key of the last completely scanned row.
	// This is so that a client may efficiently scan to where the request left off in a subsequent
	// call to ReadRows in the case where many rows were processed, but because of the transform, no
	// output was generated.
	LastInputRow []byte `protobuf:"bytes,2,opt,name=last_input_row,json=lastInputRow,proto3" json:"last_input_row,omitempty"`
	// similar to last_input_row, the last_accumulator returns the last accumulator from a transform
	// of intput -> output. This combined with last_row allows a client to call ReadRows again
	// and pick up where the last call left off.
	LastAccumulator string `protobuf:"bytes,3,opt,name=last_accumulator,json=lastAccumulator" json:"last_accumulator,omitempty"`
}

func (m *ReadRowsReply) Reset()                    { *m = ReadRowsReply{} }
func (m *ReadRowsReply) String() string            { return proto.CompactTextString(m) }
func (*ReadRowsReply) ProtoMessage()               {}
func (*ReadRowsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ReadRowsReply) GetRows() []string {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *ReadRowsReply) GetLastInputRow() []byte {
	if m != nil {
		return m.LastInputRow
	}
	return nil
}

func (m *ReadRowsReply) GetLastAccumulator() string {
	if m != nil {
		return m.LastAccumulator
	}
	return ""
}

func init() {
	proto.RegisterType((*GetNodesRequest)(nil), "edge.GetNodesRequest")
	proto.RegisterType((*GetNodesReply)(nil), "edge.GetNodesReply")
	proto.RegisterType((*GetIngressesRequest)(nil), "edge.GetIngressesRequest")
	proto.RegisterType((*GetIngressesReply)(nil), "edge.GetIngressesReply")
	proto.RegisterType((*MakeTransformerRequest)(nil), "edge.MakeTransformerRequest")
	proto.RegisterType((*MakeTransformerReply)(nil), "edge.MakeTransformerReply")
	proto.RegisterType((*ReadRowsRequest)(nil), "edge.ReadRowsRequest")
	proto.RegisterType((*ReadRowsReply)(nil), "edge.ReadRowsReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Edge service

type EdgeClient interface {
	GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*GetNodesReply, error)
	ReadRows(ctx context.Context, in *ReadRowsRequest, opts ...grpc.CallOption) (Edge_ReadRowsClient, error)
	MakeTransformer(ctx context.Context, in *MakeTransformerRequest, opts ...grpc.CallOption) (*MakeTransformerReply, error)
	GetIngresses(ctx context.Context, in *GetIngressesRequest, opts ...grpc.CallOption) (*GetIngressesReply, error)
}

type edgeClient struct {
	cc *grpc.ClientConn
}

func NewEdgeClient(cc *grpc.ClientConn) EdgeClient {
	return &edgeClient{cc}
}

func (c *edgeClient) GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*GetNodesReply, error) {
	out := new(GetNodesReply)
	err := grpc.Invoke(ctx, "/edge.Edge/GetNodes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeClient) ReadRows(ctx context.Context, in *ReadRowsRequest, opts ...grpc.CallOption) (Edge_ReadRowsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Edge_serviceDesc.Streams[0], c.cc, "/edge.Edge/ReadRows", opts...)
	if err != nil {
		return nil, err
	}
	x := &edgeReadRowsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Edge_ReadRowsClient interface {
	Recv() (*ReadRowsReply, error)
	grpc.ClientStream
}

type edgeReadRowsClient struct {
	grpc.ClientStream
}

func (x *edgeReadRowsClient) Recv() (*ReadRowsReply, error) {
	m := new(ReadRowsReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *edgeClient) MakeTransformer(ctx context.Context, in *MakeTransformerRequest, opts ...grpc.CallOption) (*MakeTransformerReply, error) {
	out := new(MakeTransformerReply)
	err := grpc.Invoke(ctx, "/edge.Edge/MakeTransformer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeClient) GetIngresses(ctx context.Context, in *GetIngressesRequest, opts ...grpc.CallOption) (*GetIngressesReply, error) {
	out := new(GetIngressesReply)
	err := grpc.Invoke(ctx, "/edge.Edge/GetIngresses", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Edge service

type EdgeServer interface {
	GetNodes(context.Context, *GetNodesRequest) (*GetNodesReply, error)
	ReadRows(*ReadRowsRequest, Edge_ReadRowsServer) error
	MakeTransformer(context.Context, *MakeTransformerRequest) (*MakeTransformerReply, error)
	GetIngresses(context.Context, *GetIngressesRequest) (*GetIngressesReply, error)
}

func RegisterEdgeServer(s *grpc.Server, srv EdgeServer) {
	s.RegisterService(&_Edge_serviceDesc, srv)
}

func _Edge_GetNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeServer).GetNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/edge.Edge/GetNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeServer).GetNodes(ctx, req.(*GetNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Edge_ReadRows_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadRowsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EdgeServer).ReadRows(m, &edgeReadRowsServer{stream})
}

type Edge_ReadRowsServer interface {
	Send(*ReadRowsReply) error
	grpc.ServerStream
}

type edgeReadRowsServer struct {
	grpc.ServerStream
}

func (x *edgeReadRowsServer) Send(m *ReadRowsReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Edge_MakeTransformer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeTransformerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeServer).MakeTransformer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/edge.Edge/MakeTransformer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeServer).MakeTransformer(ctx, req.(*MakeTransformerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Edge_GetIngresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIngressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeServer).GetIngresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/edge.Edge/GetIngresses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeServer).GetIngresses(ctx, req.(*GetIngressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Edge_serviceDesc = grpc.ServiceDesc{
	ServiceName: "edge.Edge",
	HandlerType: (*EdgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNodes",
			Handler:    _Edge_GetNodes_Handler,
		},
		{
			MethodName: "MakeTransformer",
			Handler:    _Edge_MakeTransformer_Handler,
		},
		{
			MethodName: "GetIngresses",
			Handler:    _Edge_GetIngresses_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadRows",
			Handler:       _Edge_ReadRows_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "edge.proto",
}

func init() { proto.RegisterFile("edge.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xcd, 0x6e, 0xd4, 0x30,
	0x10, 0xc7, 0x9b, 0x4d, 0x5a, 0x75, 0x87, 0xfd, 0x68, 0xa7, 0x05, 0x42, 0x54, 0xa1, 0xc8, 0xa2,
	0x28, 0xbd, 0x54, 0x7c, 0x5c, 0x10, 0x37, 0x24, 0x50, 0xb5, 0x12, 0xe5, 0x60, 0x71, 0x5f, 0x99,
	0xb5, 0x59, 0x19, 0xb2, 0x71, 0xb0, 0x1d, 0xa2, 0x3e, 0x06, 0xef, 0xc1, 0x43, 0x22, 0x3b, 0x9b,
	0x26, 0x0d, 0xed, 0xde, 0x66, 0x7e, 0x1e, 0xcf, 0xfc, 0x3d, 0xf9, 0x07, 0x40, 0xf0, 0xb5, 0xb8,
	0x2c, 0xb5, 0xb2, 0x0a, 0x23, 0x17, 0x93, 0x63, 0x98, 0x5f, 0x09, 0xfb, 0x45, 0x71, 0x61, 0xa8,
	0xf8, 0x55, 0x09, 0x63, 0xc9, 0x39, 0x4c, 0x3b, 0x54, 0xe6, 0x37, 0x78, 0x0a, 0xfb, 0x85, 0xcb,
	0xe2, 0x20, 0x0d, 0xb3, 0x31, 0x6d, 0x12, 0x72, 0x01, 0x27, 0x57, 0xc2, 0x2e, 0x8a, 0xb5, 0x16,
	0xc6, 0xdc, 0xde, 0x46, 0x84, 0xc8, 0x9d, 0xc7, 0x41, 0x1a, 0x64, 0x63, 0xea, 0x63, 0xf2, 0x1a,
	0x8e, 0xef, 0x96, 0xba, 0xae, 0x67, 0x30, 0x96, 0x2d, 0xd9, 0x76, 0xee, 0x00, 0xf9, 0x0c, 0x4f,
	0xae, 0xd9, 0x4f, 0xf1, 0x55, 0xb3, 0xc2, 0x7c, 0x57, 0x7a, 0x23, 0xf4, 0x8e, 0x01, 0xf8, 0x1c,
	0xe0, 0x07, 0xfb, 0xcd, 0xcc, 0x4a, 0xcb, 0xd2, 0xc6, 0xa3, 0x34, 0xc8, 0x26, 0xb4, 0x47, 0xc8,
	0x4b, 0x38, 0xfd, 0xaf, 0x9b, 0xd3, 0x30, 0x83, 0x91, 0xe4, 0xdb, 0x4e, 0x23, 0xc9, 0xc9, 0xdf,
	0x00, 0xe6, 0x54, 0x30, 0x4e, 0x55, 0xbd, 0xeb, 0x41, 0x6e, 0x23, 0xc6, 0x32, 0xdd, 0x8e, 0x6a,
	0x12, 0x3c, 0x82, 0x50, 0x14, 0x3c, 0x0e, 0x3d, 0x73, 0x21, 0x9e, 0xc3, 0xcc, 0x76, 0x33, 0x97,
	0x92, 0xc7, 0x91, 0xef, 0x32, 0xed, 0xd1, 0x05, 0xc7, 0x14, 0x1e, 0xb1, 0xd5, 0xaa, 0xda, 0x54,
	0x39, 0xb3, 0x4a, 0xc7, 0xfb, 0xbe, 0xa6, 0x8f, 0xdc, 0xc0, 0x5c, 0x6e, 0xa4, 0x8d, 0x0f, 0xd2,
	0x20, 0x0b, 0x69, 0x93, 0x10, 0x0b, 0xd3, 0x4e, 0xad, 0x7b, 0x0f, 0x42, 0xa4, 0x55, 0xdd, 0xae,
	0xd3, 0xc7, 0xf8, 0x02, 0x66, 0x39, 0x33, 0x76, 0x29, 0x8b, 0xb2, 0xb2, 0x4b, 0xad, 0xea, 0xad,
	0xe8, 0x89, 0xa3, 0x0b, 0x07, 0xa9, 0xaa, 0xf1, 0x02, 0x8e, 0x7c, 0x55, 0x5f, 0x47, 0xe8, 0x75,
	0xcc, 0x1d, 0xff, 0xd0, 0xe1, 0x37, 0x7f, 0x46, 0x10, 0x7d, 0xe2, 0x6b, 0x81, 0xef, 0xe0, 0xb0,
	0x35, 0x0a, 0x3e, 0xbe, 0xf4, 0xd6, 0x1a, 0x78, 0x29, 0x39, 0x19, 0xe2, 0x32, 0xbf, 0x21, 0x7b,
	0xf8, 0x1e, 0x0e, 0x5b, 0xe1, 0xed, 0xcd, 0xc1, 0xda, 0xdb, 0x9b, 0x77, 0xde, 0x47, 0xf6, 0x5e,
	0x05, 0x78, 0x0d, 0xf3, 0xc1, 0xb7, 0xc4, 0xb3, 0xa6, 0xf6, 0x7e, 0xc3, 0x24, 0xc9, 0x03, 0xa7,
	0x8d, 0x94, 0x8f, 0x30, 0xe9, 0x7b, 0x13, 0x9f, 0xdd, 0x2a, 0x1e, 0x5a, 0x3b, 0x79, 0x7a, 0xdf,
	0x91, 0xef, 0xf2, 0xed, 0xc0, 0xff, 0x53, 0x6f, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x70, 0x6a,
	0xab, 0xd1, 0x61, 0x03, 0x00, 0x00,
}
