// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function bmin(b) {
  if (b) {
    return b[0][/* lte */0];
  } else {
    return Pervasives.max_float;
  }
}

function bmax(_b) {
  while(true) {
    var b = _b;
    if (b) {
      var rest = b[1];
      if (rest) {
        _b = rest;
        continue ;
        
      } else {
        return b[0][/* lte */0];
      }
    } else {
      return Pervasives.min_float;
    }
  };
}

function hmin(h) {
  return bmin(h[/* buckets */0]);
}

function hmax(h) {
  return bmax(h[/* buckets */0]);
}

exports.bmin = bmin;
exports.bmax = bmax;
exports.hmin = hmin;
exports.hmax = hmax;
/* No side effect */
