// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ChromaJs = require("chroma-js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Chroma$ReactTemplate = require("./Chroma.bs.js");

var component = ReasonReact.statelessComponent("Cell");

var schema = Curry._3(Chroma$ReactTemplate.Scale[/* domain */0], ChromaJs.scale("PuRd"), 1.0, 0.0);

function make(intensity, top, left, bottom, right, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var fill = Curry._2(Chroma$ReactTemplate.Scale[/* hex */1], schema, intensity);
      return React.createElement("rect", {
                  height: Pervasives.string_of_float(top - bottom),
                  width: Pervasives.string_of_float(right - left),
                  fill: fill,
                  stroke: "black",
                  strokeWidth: "0.1",
                  x: Pervasives.string_of_float(left),
                  y: Pervasives.string_of_float(100.0 - top)
                });
    });
  return newrecord;
}

exports.component = component;
exports.schema = schema;
exports.make = make;
/* component Not a pure module */
