// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Cell$ReactTemplate = require("./Cell.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement("svg", {
          height: "300",
          width: "300",
          viewBox: "0 0 100 100"
        }, ReasonReact.element(/* None */0, /* None */0, Cell$ReactTemplate.make(0.4, 95.0, 0.0, 5.0, 15.0, /* array */[])), ReasonReact.element(/* None */0, /* None */0, Cell$ReactTemplate.make(0.8, 25.0, 25.0, 5.0, 50.0, /* array */[])), ReasonReact.element(/* None */0, /* None */0, Cell$ReactTemplate.make(0.1, 35.0, 25.0, 25.0, 50.0, /* array */[])), ReasonReact.element(/* None */0, /* None */0, Cell$ReactTemplate.make(0.01, 36.0, 25.0, 35.0, 50.0, /* array */[])), ReasonReact.element(/* None */0, /* None */0, Cell$ReactTemplate.make(0.2, 40.0, 25.0, 36.0, 50.0, /* array */[])), ReasonReact.element(/* None */0, /* None */0, Cell$ReactTemplate.make(0.5, 60.0, 25.0, 40.0, 50.0, /* array */[])), ReasonReact.element(/* None */0, /* None */0, Cell$ReactTemplate.make(0.8, 62.0, 25.0, 60.0, 50.0, /* array */[]))), "index");

/*  Not a pure module */
