// Code generated by protoc-gen-go. DO NOT EDIT.
// source: emitio.proto

/*
Package emitio is a generated protocol buffer package.

It is generated from these files:
	emitio.proto

It has these top-level messages:
	InfoRequest
	InfoReply
	MakeTransformerRequest
	MakeTransformerReply
	ReadRowsRequest
	ReadRowsReply
*/
package emitio

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InfoRequest struct {
}

func (m *InfoRequest) Reset()                    { *m = InfoRequest{} }
func (m *InfoRequest) String() string            { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()               {}
func (*InfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type InfoReply struct {
	Key       string            `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Id        string            `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Origin    map[string]string `protobuf:"bytes,3,rep,name=origin" json:"origin,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ingresses []string          `protobuf:"bytes,4,rep,name=ingresses" json:"ingresses,omitempty"`
}

func (m *InfoReply) Reset()                    { *m = InfoReply{} }
func (m *InfoReply) String() string            { return proto.CompactTextString(m) }
func (*InfoReply) ProtoMessage()               {}
func (*InfoReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InfoReply) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *InfoReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *InfoReply) GetOrigin() map[string]string {
	if m != nil {
		return m.Origin
	}
	return nil
}

func (m *InfoReply) GetIngresses() []string {
	if m != nil {
		return m.Ingresses
	}
	return nil
}

type MakeTransformerRequest struct {
	Javascript []byte `protobuf:"bytes,1,opt,name=javascript,proto3" json:"javascript,omitempty"`
}

func (m *MakeTransformerRequest) Reset()                    { *m = MakeTransformerRequest{} }
func (m *MakeTransformerRequest) String() string            { return proto.CompactTextString(m) }
func (*MakeTransformerRequest) ProtoMessage()               {}
func (*MakeTransformerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MakeTransformerRequest) GetJavascript() []byte {
	if m != nil {
		return m.Javascript
	}
	return nil
}

type MakeTransformerReply struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *MakeTransformerReply) Reset()                    { *m = MakeTransformerReply{} }
func (m *MakeTransformerReply) String() string            { return proto.CompactTextString(m) }
func (*MakeTransformerReply) ProtoMessage()               {}
func (*MakeTransformerReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MakeTransformerReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadRowsRequest struct {
	Start         []byte `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           []byte `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	TransformerId string `protobuf:"bytes,3,opt,name=transformer_id,json=transformerId" json:"transformer_id,omitempty"`
	Accumulator   string `protobuf:"bytes,4,opt,name=accumulator" json:"accumulator,omitempty"`
	// max number of rows to be processed by the transformer before sending a ReadRowsReply
	InputLimit uint32 `protobuf:"varint,5,opt,name=input_limit,json=inputLimit" json:"input_limit,omitempty"`
	// max number of rows to be produced by the transformer before sending a ReadRowsReply. Note,
	// a single input may produce many output lines, so the ReadRowsReply may have more than this
	// limit in its reply, but once it crosses the limit the ReadRowsReply will be sent.
	OutputLimit uint32 `protobuf:"varint,6,opt,name=output_limit,json=outputLimit" json:"output_limit,omitempty"`
	// max duration in seconds before a ReadRowsReply is sent
	MaxDuration float64 `protobuf:"fixed64,7,opt,name=max_duration,json=maxDuration" json:"max_duration,omitempty"`
}

func (m *ReadRowsRequest) Reset()                    { *m = ReadRowsRequest{} }
func (m *ReadRowsRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRowsRequest) ProtoMessage()               {}
func (*ReadRowsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadRowsRequest) GetStart() []byte {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *ReadRowsRequest) GetEnd() []byte {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *ReadRowsRequest) GetTransformerId() string {
	if m != nil {
		return m.TransformerId
	}
	return ""
}

func (m *ReadRowsRequest) GetAccumulator() string {
	if m != nil {
		return m.Accumulator
	}
	return ""
}

func (m *ReadRowsRequest) GetInputLimit() uint32 {
	if m != nil {
		return m.InputLimit
	}
	return 0
}

func (m *ReadRowsRequest) GetOutputLimit() uint32 {
	if m != nil {
		return m.OutputLimit
	}
	return 0
}

func (m *ReadRowsRequest) GetMaxDuration() float64 {
	if m != nil {
		return m.MaxDuration
	}
	return 0
}

type ReadRowsReply struct {
	Rows []string `protobuf:"bytes,1,rep,name=rows" json:"rows,omitempty"`
	// optionally, the server might return the row key of the last completely scanned row.
	// This is so that a client may efficiently scan to where the request left off in a subsequent
	// call to ReadRows in the case where many rows were processed, but because of the transform, no
	// output was generated.
	LastInputRowKey []byte `protobuf:"bytes,2,opt,name=last_input_row_key,json=lastInputRowKey,proto3" json:"last_input_row_key,omitempty"`
	// similar to last_input_row, the last_accumulator returns the last accumulator from a transform
	// of intput -> output. This combined with last_row allows a client to call ReadRows again
	// and pick up where the last call left off.
	LastAccumulator string `protobuf:"bytes,3,opt,name=last_accumulator,json=lastAccumulator" json:"last_accumulator,omitempty"`
}

func (m *ReadRowsReply) Reset()                    { *m = ReadRowsReply{} }
func (m *ReadRowsReply) String() string            { return proto.CompactTextString(m) }
func (*ReadRowsReply) ProtoMessage()               {}
func (*ReadRowsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ReadRowsReply) GetRows() []string {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *ReadRowsReply) GetLastInputRowKey() []byte {
	if m != nil {
		return m.LastInputRowKey
	}
	return nil
}

func (m *ReadRowsReply) GetLastAccumulator() string {
	if m != nil {
		return m.LastAccumulator
	}
	return ""
}

func init() {
	proto.RegisterType((*InfoRequest)(nil), "emitio.InfoRequest")
	proto.RegisterType((*InfoReply)(nil), "emitio.InfoReply")
	proto.RegisterType((*MakeTransformerRequest)(nil), "emitio.MakeTransformerRequest")
	proto.RegisterType((*MakeTransformerReply)(nil), "emitio.MakeTransformerReply")
	proto.RegisterType((*ReadRowsRequest)(nil), "emitio.ReadRowsRequest")
	proto.RegisterType((*ReadRowsReply)(nil), "emitio.ReadRowsReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Emitio service

type EmitioClient interface {
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoReply, error)
	MakeTransformer(ctx context.Context, in *MakeTransformerRequest, opts ...grpc.CallOption) (*MakeTransformerReply, error)
	ReadRows(ctx context.Context, in *ReadRowsRequest, opts ...grpc.CallOption) (Emitio_ReadRowsClient, error)
}

type emitioClient struct {
	cc *grpc.ClientConn
}

func NewEmitioClient(cc *grpc.ClientConn) EmitioClient {
	return &emitioClient{cc}
}

func (c *emitioClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoReply, error) {
	out := new(InfoReply)
	err := grpc.Invoke(ctx, "/emitio.Emitio/Info", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emitioClient) MakeTransformer(ctx context.Context, in *MakeTransformerRequest, opts ...grpc.CallOption) (*MakeTransformerReply, error) {
	out := new(MakeTransformerReply)
	err := grpc.Invoke(ctx, "/emitio.Emitio/MakeTransformer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emitioClient) ReadRows(ctx context.Context, in *ReadRowsRequest, opts ...grpc.CallOption) (Emitio_ReadRowsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Emitio_serviceDesc.Streams[0], c.cc, "/emitio.Emitio/ReadRows", opts...)
	if err != nil {
		return nil, err
	}
	x := &emitioReadRowsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Emitio_ReadRowsClient interface {
	Recv() (*ReadRowsReply, error)
	grpc.ClientStream
}

type emitioReadRowsClient struct {
	grpc.ClientStream
}

func (x *emitioReadRowsClient) Recv() (*ReadRowsReply, error) {
	m := new(ReadRowsReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Emitio service

type EmitioServer interface {
	Info(context.Context, *InfoRequest) (*InfoReply, error)
	MakeTransformer(context.Context, *MakeTransformerRequest) (*MakeTransformerReply, error)
	ReadRows(*ReadRowsRequest, Emitio_ReadRowsServer) error
}

func RegisterEmitioServer(s *grpc.Server, srv EmitioServer) {
	s.RegisterService(&_Emitio_serviceDesc, srv)
}

func _Emitio_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmitioServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emitio.Emitio/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmitioServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Emitio_MakeTransformer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeTransformerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmitioServer).MakeTransformer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emitio.Emitio/MakeTransformer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmitioServer).MakeTransformer(ctx, req.(*MakeTransformerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Emitio_ReadRows_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadRowsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EmitioServer).ReadRows(m, &emitioReadRowsServer{stream})
}

type Emitio_ReadRowsServer interface {
	Send(*ReadRowsReply) error
	grpc.ServerStream
}

type emitioReadRowsServer struct {
	grpc.ServerStream
}

func (x *emitioReadRowsServer) Send(m *ReadRowsReply) error {
	return x.ServerStream.SendMsg(m)
}

var _Emitio_serviceDesc = grpc.ServiceDesc{
	ServiceName: "emitio.Emitio",
	HandlerType: (*EmitioServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _Emitio_Info_Handler,
		},
		{
			MethodName: "MakeTransformer",
			Handler:    _Emitio_MakeTransformer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadRows",
			Handler:       _Emitio_ReadRows_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "emitio.proto",
}

func init() { proto.RegisterFile("emitio.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 482 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0xc5, 0x4d, 0x1b, 0xe8, 0x4d, 0xbb, 0x0e, 0x53, 0x20, 0xaa, 0xc6, 0x08, 0x91, 0x40, 0x41,
	0x48, 0xd5, 0x34, 0x84, 0x34, 0x78, 0x40, 0x42, 0x62, 0x0f, 0x15, 0x20, 0x84, 0xc5, 0x7b, 0x64,
	0x1a, 0x6f, 0x32, 0x4b, 0xe2, 0x62, 0x3b, 0xeb, 0x2a, 0xbe, 0x8d, 0x4f, 0xe0, 0x43, 0xf8, 0x0b,
	0x64, 0x3b, 0x59, 0xc2, 0x5a, 0xde, 0x7c, 0xcf, 0x3d, 0x3e, 0xb9, 0xf7, 0xf8, 0x04, 0x46, 0xac,
	0xe0, 0x9a, 0x8b, 0xf9, 0x4a, 0x0a, 0x2d, 0xb0, 0xef, 0xaa, 0x78, 0x0c, 0xc1, 0xa2, 0x3c, 0x13,
	0x84, 0xfd, 0xa8, 0x98, 0xd2, 0xf1, 0x2f, 0x04, 0x43, 0x57, 0xaf, 0xf2, 0x0d, 0xde, 0x07, 0xef,
	0x82, 0x6d, 0x42, 0x14, 0xa1, 0x64, 0x48, 0xcc, 0x11, 0xef, 0x41, 0x8f, 0x67, 0x61, 0xcf, 0x02,
	0x3d, 0x9e, 0xe1, 0x57, 0xe0, 0x0b, 0xc9, 0xcf, 0x79, 0x19, 0x7a, 0x91, 0x97, 0x04, 0xc7, 0x8f,
	0xe6, 0xf5, 0x57, 0xae, 0x45, 0xe6, 0x9f, 0x6d, 0xff, 0xb4, 0xd4, 0x72, 0x43, 0x6a, 0x32, 0x3e,
	0x80, 0x21, 0x2f, 0xcf, 0x25, 0x53, 0x8a, 0xa9, 0xb0, 0x1f, 0x79, 0xc9, 0x90, 0xb4, 0xc0, 0xec,
	0x35, 0x04, 0x9d, 0x4b, 0x3b, 0xa6, 0x98, 0xc2, 0xe0, 0x92, 0xe6, 0x15, 0xab, 0x07, 0x71, 0xc5,
	0x9b, 0xde, 0x09, 0x8a, 0x4f, 0xe0, 0xc1, 0x27, 0x7a, 0xc1, 0xbe, 0x4a, 0x5a, 0xaa, 0x33, 0x21,
	0x0b, 0x26, 0xeb, 0xcd, 0xf0, 0x21, 0xc0, 0x77, 0x7a, 0x49, 0xd5, 0x52, 0xf2, 0x95, 0xb6, 0x62,
	0x23, 0xd2, 0x41, 0xe2, 0x67, 0x30, 0xdd, 0xba, 0x69, 0x3c, 0x70, 0x1b, 0xa3, 0x66, 0xe3, 0xf8,
	0x0f, 0x82, 0x09, 0x61, 0x34, 0x23, 0x62, 0xad, 0x1a, 0xed, 0x29, 0x0c, 0x94, 0xa6, 0xb2, 0x91,
	0x75, 0x85, 0x99, 0x9b, 0x95, 0xce, 0xac, 0x11, 0x31, 0x47, 0xfc, 0x14, 0xf6, 0x74, 0xab, 0x9f,
	0xf2, 0x2c, 0xf4, 0xac, 0xee, 0xb8, 0x83, 0x2e, 0x32, 0x1c, 0x41, 0x40, 0x97, 0xcb, 0xaa, 0xa8,
	0x72, 0xaa, 0x85, 0x0c, 0xfb, 0x96, 0xd3, 0x85, 0xf0, 0x63, 0x08, 0x78, 0xb9, 0xaa, 0x74, 0x9a,
	0xf3, 0x82, 0xeb, 0x70, 0x10, 0xa1, 0x64, 0x4c, 0xc0, 0x42, 0x1f, 0x0d, 0x82, 0x9f, 0xc0, 0x48,
	0x54, 0xba, 0x65, 0xf8, 0x96, 0x11, 0x38, 0xec, 0x9a, 0x52, 0xd0, 0xab, 0x34, 0xab, 0x24, 0xd5,
	0x5c, 0x94, 0xe1, 0xed, 0x08, 0x25, 0x88, 0x04, 0x05, 0xbd, 0x7a, 0x5f, 0x43, 0xf1, 0x4f, 0x18,
	0xb7, 0xab, 0x1a, 0x33, 0x30, 0xf4, 0xa5, 0x58, 0xab, 0x10, 0xd9, 0x27, 0xb3, 0x67, 0xfc, 0x02,
	0x70, 0x4e, 0x95, 0x4e, 0xdd, 0x40, 0x52, 0xac, 0x53, 0xf3, 0x5a, 0x6e, 0xeb, 0x89, 0xe9, 0x2c,
	0x4c, 0x83, 0x88, 0xf5, 0x07, 0xb6, 0xc1, 0xcf, 0x61, 0xdf, 0x92, 0xbb, 0xfb, 0x39, 0x0f, 0x2c,
	0xf5, 0x5d, 0x0b, 0x1f, 0xff, 0x46, 0xe0, 0x9f, 0xda, 0x30, 0xe1, 0x23, 0xe8, 0x9b, 0x3c, 0xe1,
	0x7b, 0xff, 0xa6, 0xcb, 0x9a, 0x3f, 0xbb, 0xbb, 0x15, 0xb9, 0xf8, 0x16, 0xfe, 0x02, 0x93, 0x1b,
	0xaf, 0x89, 0x0f, 0x1b, 0xde, 0xee, 0x80, 0xcc, 0x0e, 0xfe, 0xdb, 0x77, 0x92, 0x6f, 0xe1, 0x4e,
	0x63, 0x06, 0x7e, 0xd8, 0x70, 0x6f, 0x24, 0x61, 0x76, 0x7f, 0xbb, 0x61, 0x6f, 0x1f, 0xa1, 0x6f,
	0xbe, 0xfd, 0xf1, 0x5e, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x4f, 0xe9, 0x1a, 0x88, 0x03,
	0x00, 0x00,
}
