// Code generated by protoc-gen-go. DO NOT EDIT.
// source: emitio.proto

/*
Package emitio is a generated protocol buffer package.

It is generated from these files:
	emitio.proto

It has these top-level messages:
	ReadRequest
	ReadReply
	InfoRequest
	InfoReply
	MakeTransformerRequest
	MakeTransformerReply
*/
package emitio

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReadRequest struct {
	Start         []byte  `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           []byte  `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	TransformerId string  `protobuf:"bytes,3,opt,name=transformer_id,json=transformerId" json:"transformer_id,omitempty"`
	Accumulator   string  `protobuf:"bytes,4,opt,name=accumulator" json:"accumulator,omitempty"`
	InputLimit    uint32  `protobuf:"varint,5,opt,name=input_limit,json=inputLimit" json:"input_limit,omitempty"`
	OutputLimit   uint32  `protobuf:"varint,6,opt,name=output_limit,json=outputLimit" json:"output_limit,omitempty"`
	DurationLimit float64 `protobuf:"fixed64,7,opt,name=duration_limit,json=durationLimit" json:"duration_limit,omitempty"`
	Tail          bool    `protobuf:"varint,8,opt,name=tail" json:"tail,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ReadRequest) GetStart() []byte {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *ReadRequest) GetEnd() []byte {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *ReadRequest) GetTransformerId() string {
	if m != nil {
		return m.TransformerId
	}
	return ""
}

func (m *ReadRequest) GetAccumulator() string {
	if m != nil {
		return m.Accumulator
	}
	return ""
}

func (m *ReadRequest) GetInputLimit() uint32 {
	if m != nil {
		return m.InputLimit
	}
	return 0
}

func (m *ReadRequest) GetOutputLimit() uint32 {
	if m != nil {
		return m.OutputLimit
	}
	return 0
}

func (m *ReadRequest) GetDurationLimit() float64 {
	if m != nil {
		return m.DurationLimit
	}
	return 0
}

func (m *ReadRequest) GetTail() bool {
	if m != nil {
		return m.Tail
	}
	return false
}

type ReadReply struct {
	Rows            []string `protobuf:"bytes,1,rep,name=rows" json:"rows,omitempty"`
	LastAccumulator string   `protobuf:"bytes,2,opt,name=last_accumulator,json=lastAccumulator" json:"last_accumulator,omitempty"`
	LastInputKey    []byte   `protobuf:"bytes,3,opt,name=last_input_key,json=lastInputKey,proto3" json:"last_input_key,omitempty"`
}

func (m *ReadReply) Reset()                    { *m = ReadReply{} }
func (m *ReadReply) String() string            { return proto.CompactTextString(m) }
func (*ReadReply) ProtoMessage()               {}
func (*ReadReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReadReply) GetRows() []string {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *ReadReply) GetLastAccumulator() string {
	if m != nil {
		return m.LastAccumulator
	}
	return ""
}

func (m *ReadReply) GetLastInputKey() []byte {
	if m != nil {
		return m.LastInputKey
	}
	return nil
}

type InfoRequest struct {
}

func (m *InfoRequest) Reset()                    { *m = InfoRequest{} }
func (m *InfoRequest) String() string            { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()               {}
func (*InfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type InfoReply struct {
	Key       string            `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Id        string            `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Origin    map[string]string `protobuf:"bytes,3,rep,name=origin" json:"origin,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ingresses []string          `protobuf:"bytes,4,rep,name=ingresses" json:"ingresses,omitempty"`
	Version   string            `protobuf:"bytes,5,opt,name=version" json:"version,omitempty"`
}

func (m *InfoReply) Reset()                    { *m = InfoReply{} }
func (m *InfoReply) String() string            { return proto.CompactTextString(m) }
func (*InfoReply) ProtoMessage()               {}
func (*InfoReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *InfoReply) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *InfoReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *InfoReply) GetOrigin() map[string]string {
	if m != nil {
		return m.Origin
	}
	return nil
}

func (m *InfoReply) GetIngresses() []string {
	if m != nil {
		return m.Ingresses
	}
	return nil
}

func (m *InfoReply) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type MakeTransformerRequest struct {
	Javascript []byte `protobuf:"bytes,1,opt,name=javascript,proto3" json:"javascript,omitempty"`
}

func (m *MakeTransformerRequest) Reset()                    { *m = MakeTransformerRequest{} }
func (m *MakeTransformerRequest) String() string            { return proto.CompactTextString(m) }
func (*MakeTransformerRequest) ProtoMessage()               {}
func (*MakeTransformerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MakeTransformerRequest) GetJavascript() []byte {
	if m != nil {
		return m.Javascript
	}
	return nil
}

type MakeTransformerReply struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *MakeTransformerReply) Reset()                    { *m = MakeTransformerReply{} }
func (m *MakeTransformerReply) String() string            { return proto.CompactTextString(m) }
func (*MakeTransformerReply) ProtoMessage()               {}
func (*MakeTransformerReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MakeTransformerReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*ReadRequest)(nil), "emitio.ReadRequest")
	proto.RegisterType((*ReadReply)(nil), "emitio.ReadReply")
	proto.RegisterType((*InfoRequest)(nil), "emitio.InfoRequest")
	proto.RegisterType((*InfoReply)(nil), "emitio.InfoReply")
	proto.RegisterType((*MakeTransformerRequest)(nil), "emitio.MakeTransformerRequest")
	proto.RegisterType((*MakeTransformerReply)(nil), "emitio.MakeTransformerReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Emitio service

type EmitioClient interface {
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoReply, error)
	MakeTransformer(ctx context.Context, in *MakeTransformerRequest, opts ...grpc.CallOption) (*MakeTransformerReply, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (Emitio_ReadClient, error)
}

type emitioClient struct {
	cc *grpc.ClientConn
}

func NewEmitioClient(cc *grpc.ClientConn) EmitioClient {
	return &emitioClient{cc}
}

func (c *emitioClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoReply, error) {
	out := new(InfoReply)
	err := grpc.Invoke(ctx, "/emitio.Emitio/Info", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emitioClient) MakeTransformer(ctx context.Context, in *MakeTransformerRequest, opts ...grpc.CallOption) (*MakeTransformerReply, error) {
	out := new(MakeTransformerReply)
	err := grpc.Invoke(ctx, "/emitio.Emitio/MakeTransformer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emitioClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (Emitio_ReadClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Emitio_serviceDesc.Streams[0], c.cc, "/emitio.Emitio/Read", opts...)
	if err != nil {
		return nil, err
	}
	x := &emitioReadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Emitio_ReadClient interface {
	Recv() (*ReadReply, error)
	grpc.ClientStream
}

type emitioReadClient struct {
	grpc.ClientStream
}

func (x *emitioReadClient) Recv() (*ReadReply, error) {
	m := new(ReadReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Emitio service

type EmitioServer interface {
	Info(context.Context, *InfoRequest) (*InfoReply, error)
	MakeTransformer(context.Context, *MakeTransformerRequest) (*MakeTransformerReply, error)
	Read(*ReadRequest, Emitio_ReadServer) error
}

func RegisterEmitioServer(s *grpc.Server, srv EmitioServer) {
	s.RegisterService(&_Emitio_serviceDesc, srv)
}

func _Emitio_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmitioServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emitio.Emitio/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmitioServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Emitio_MakeTransformer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeTransformerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmitioServer).MakeTransformer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emitio.Emitio/MakeTransformer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmitioServer).MakeTransformer(ctx, req.(*MakeTransformerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Emitio_Read_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EmitioServer).Read(m, &emitioReadServer{stream})
}

type Emitio_ReadServer interface {
	Send(*ReadReply) error
	grpc.ServerStream
}

type emitioReadServer struct {
	grpc.ServerStream
}

func (x *emitioReadServer) Send(m *ReadReply) error {
	return x.ServerStream.SendMsg(m)
}

var _Emitio_serviceDesc = grpc.ServiceDesc{
	ServiceName: "emitio.Emitio",
	HandlerType: (*EmitioServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _Emitio_Info_Handler,
		},
		{
			MethodName: "MakeTransformer",
			Handler:    _Emitio_MakeTransformer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Read",
			Handler:       _Emitio_Read_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "emitio.proto",
}

func init() { proto.RegisterFile("emitio.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 494 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x51, 0x6f, 0xd3, 0x30,
	0x10, 0x9e, 0x9b, 0xb6, 0x5b, 0x2e, 0x6d, 0x57, 0x4c, 0x85, 0xac, 0x6a, 0x8c, 0x10, 0x31, 0x14,
	0x5e, 0xaa, 0xa9, 0x08, 0x69, 0xf0, 0xc6, 0xc3, 0x1e, 0x2a, 0x40, 0x08, 0x8b, 0xf7, 0xca, 0x34,
	0xde, 0x64, 0x96, 0xc6, 0xc1, 0x76, 0x8a, 0xfa, 0xf3, 0xf8, 0x15, 0xfc, 0x1a, 0x24, 0x64, 0x3b,
	0x59, 0x02, 0xdb, 0xde, 0xee, 0x3e, 0x7f, 0xbe, 0xbb, 0xef, 0xf3, 0x19, 0x46, 0x7c, 0x2b, 0x8c,
	0x90, 0x8b, 0x52, 0x49, 0x23, 0xf1, 0xd0, 0x67, 0xc9, 0x1f, 0x04, 0x11, 0xe5, 0x2c, 0xa3, 0xfc,
	0x47, 0xc5, 0xb5, 0xc1, 0x33, 0x18, 0x68, 0xc3, 0x94, 0x21, 0x28, 0x46, 0xe9, 0x88, 0xfa, 0x04,
	0x4f, 0x21, 0xe0, 0x45, 0x46, 0x7a, 0x0e, 0xb3, 0x21, 0x3e, 0x83, 0x89, 0x51, 0xac, 0xd0, 0x57,
	0x52, 0x6d, 0xb9, 0x5a, 0x8b, 0x8c, 0x04, 0x31, 0x4a, 0x43, 0x3a, 0xee, 0xa0, 0xab, 0x0c, 0xc7,
	0x10, 0xb1, 0xcd, 0xa6, 0xda, 0x56, 0x39, 0x33, 0x52, 0x91, 0xbe, 0xe3, 0x74, 0x21, 0xfc, 0x0c,
	0x22, 0x51, 0x94, 0x95, 0x59, 0xe7, 0x62, 0x2b, 0x0c, 0x19, 0xc4, 0x28, 0x1d, 0x53, 0x70, 0xd0,
	0x47, 0x8b, 0xe0, 0xe7, 0x30, 0x92, 0x95, 0x69, 0x19, 0x43, 0xc7, 0x88, 0x3c, 0xe6, 0x29, 0x67,
	0x30, 0xc9, 0x2a, 0xc5, 0x8c, 0x90, 0x45, 0x4d, 0x3a, 0x8c, 0x51, 0x8a, 0xe8, 0xb8, 0x41, 0x3d,
	0x0d, 0x43, 0xdf, 0x30, 0x91, 0x93, 0xa3, 0x18, 0xa5, 0x47, 0xd4, 0xc5, 0x49, 0x09, 0xa1, 0x97,
	0x5f, 0xe6, 0x7b, 0x4b, 0x50, 0xf2, 0xa7, 0x26, 0x28, 0x0e, 0xd2, 0x90, 0xba, 0x18, 0xbf, 0x82,
	0x69, 0xce, 0xb4, 0x59, 0x77, 0x65, 0xf4, 0x9c, 0x8c, 0x63, 0x8b, 0xbf, 0xef, 0x48, 0x79, 0x01,
	0x13, 0x47, 0xf5, 0x7a, 0x6e, 0xf8, 0xde, 0x79, 0x32, 0xa2, 0x23, 0x8b, 0xae, 0x2c, 0xf8, 0x81,
	0xef, 0x93, 0x31, 0x44, 0xab, 0xe2, 0x4a, 0xd6, 0x86, 0x27, 0xbf, 0x11, 0x84, 0x3e, 0xb7, 0x13,
	0x4c, 0x21, 0xb0, 0xf7, 0x90, 0x6b, 0x60, 0x43, 0x3c, 0x81, 0x9e, 0xc8, 0xea, 0x8e, 0x3d, 0x91,
	0xe1, 0x37, 0x30, 0x94, 0x4a, 0x5c, 0x8b, 0x82, 0x04, 0x71, 0x90, 0x46, 0xcb, 0xa7, 0x8b, 0xfa,
	0x5d, 0x6f, 0x8b, 0x2c, 0x3e, 0xbb, 0xf3, 0xcb, 0xc2, 0xa8, 0x3d, 0xad, 0xc9, 0xf8, 0x04, 0x42,
	0x51, 0x5c, 0x2b, 0xae, 0x35, 0xd7, 0xa4, 0xef, 0xf4, 0xb5, 0x00, 0x26, 0x70, 0xb8, 0xe3, 0x4a,
	0x0b, 0x59, 0xb8, 0x07, 0x08, 0x69, 0x93, 0xce, 0xdf, 0x42, 0xd4, 0x29, 0x77, 0xcf, 0x7c, 0x33,
	0x18, 0xec, 0x58, 0x5e, 0xf1, 0x7a, 0x44, 0x9f, 0xbc, 0xeb, 0x5d, 0xa0, 0xe4, 0x02, 0x9e, 0x7c,
	0x62, 0x37, 0xfc, 0x6b, 0xbb, 0x10, 0xcd, 0x92, 0x9d, 0x02, 0x7c, 0x67, 0x3b, 0xa6, 0x37, 0x4a,
	0x94, 0xcd, 0xa6, 0x75, 0x90, 0xe4, 0x25, 0xcc, 0xee, 0xdc, 0xb4, 0xee, 0x78, 0x2f, 0x50, 0xe3,
	0xc5, 0xf2, 0x17, 0x82, 0xe1, 0xa5, 0x53, 0x8f, 0xcf, 0xa1, 0x6f, 0x0d, 0xc0, 0x8f, 0xff, 0xb5,
	0xc3, 0xf5, 0x9b, 0x3f, 0xba, 0xe3, 0x51, 0x72, 0x80, 0xbf, 0xc0, 0xf1, 0x7f, 0x4d, 0xf0, 0x69,
	0xc3, 0xbb, 0x7f, 0xee, 0xf9, 0xc9, 0x83, 0xe7, 0xbe, 0xe4, 0x12, 0xfa, 0x76, 0x99, 0xda, 0x21,
	0x3a, 0x3f, 0xab, 0x1d, 0xe2, 0x76, 0xdf, 0x92, 0x83, 0x73, 0xf4, 0x6d, 0xe8, 0xfe, 0xe3, 0xeb,
	0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7d, 0xd8, 0x6d, 0xdc, 0x9f, 0x03, 0x00, 0x00,
}
